Output timestamps
deltachat/login-demo pull request #9
Opened 2020-02-04 08:34 UTC by missytake

For a more verbose log output. Timestamps are useful at debugging failed login attempts.

2020-02-04 08:38 UTC, missytake commented
I deployed this branch to login.testrun.org, it seems to work :)

2020-02-04 08:42 UTC, pabzm requested changes
Looks good, thanks!

But 53d174b2be2ff19bb9380f6ee0968c7f74192ab4 ("update core") is not related to this change, please remove that commit.

2020-02-04 08:46 UTC, missytake commented
Isn't the state of package-lock.json with which the changes worked important? I don't know much about node.js, but at desktop I was once asked to build a GitHub action to specifically remind developers that they should push the results of `npm i` as well... just interested :)

2020-02-04 08:55 UTC, pabzm commented
Yes, please include `package-lock.json`. But you changed the versions of DC core, too. And that change does not belong into one PR with introducing timestamps —  unless there is a technical dependency, which I'm unaware of.

2020-02-04 08:56 UTC, missytake commented
okay. do we still want to upgrade core afterwards though?

2020-02-04 08:59 UTC, missytake commented
I think we need to do it for #5 anyway

2020-02-04 13:32 UTC, pabzm commented
> okay. do we still want to upgrade core afterwards though?

I guess so, yes. But I'm trying to push for clean, small PRs, that cover one topic only.

2020-02-04 13:41 UTC, pabzm requested changes
After fixing the core-version strings, could you clean the commit history so that only the necessary commits stay in the history? E.g. drop both the commits that change and revert a thing.

2020-02-04 13:41 UTC, pabzm commented on package.json
> +    "deltachat-node": "1.0.0-alpha.11",
The master-branch has `^1.0.0-beta.15`, so that shouldn't be changed in this PR.

2020-02-04 13:41 UTC, pabzm commented on package-lock.json
> +      "integrity": "sha512-L9yisI+xd/mLEQEsg1Or+CwdXFkBFr60zBC22sfPef0gedTmtQc0yRUFTRVGwbTTHvDenEUwx9P7fkwSh2eWKA==",
This shouldn't be changed in this PR.

2020-02-04 14:48 UTC, Simon-Laux commented
Tip: you can also replace the log function to sth. like:

```js
function log (...args) {
console.log(`[${(new Date()).toLocaleString("en-US")}]`,...args);
}
```

2020-02-05 09:43 UTC, missytake commented
closing this in favor of #10

2020-02-05 09:43 UTC, closed without merging